### Arrays creation

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(2,3)

array([[0.9266365 , 0.96844054, 0.06629788],
       [0.90308479, 0.99634833, 0.92646448]])

In [13]:
arr = np.random.randint(0,10,(2,3))
print(arr)

[[7 8 5]
 [3 2 9]]


In [17]:
arr.shape
arr.size
arr.dtype
arr.ndim

2

### Indexing and Slicing

In [19]:
arr = np.random.randint(1,10,(3,5))
print(arr)

[[8 7 6 2 7]
 [7 7 2 2 1]
 [3 3 2 9 2]]


In [33]:
arr[0]
arr[1:2]
arr[:,-1]
arr[0,1]

np.int32(7)

### Reshaping Arrays

In [36]:
arr = np.random.randint(0,100,(3,5))
print(arr)

[[31 29  7 59 28]
 [53 76 13  7 32]
 [33 76 44 59 55]]


In [38]:
arr.reshape(5,3)

array([[31, 29,  7],
       [59, 28, 53],
       [76, 13,  7],
       [32, 33, 76],
       [44, 59, 55]], dtype=int32)

In [39]:
arr.flatten()

array([31, 29,  7, 59, 28, 53, 76, 13,  7, 32, 33, 76, 44, 59, 55],
      dtype=int32)

In [ ]:
arr.ravel() # ravel is similar to flatten but it returns a view of the original array if possible, while flatten always returns a copy.

array([31, 29,  7, 59, 28, 53, 76, 13,  7, 32, 33, 76, 44, 59, 55],
      dtype=int32)

### Mathematical Operations

In [ ]:
arr = np.random.randint(0,100,(3,5))
print(arr)

[[64 26 24 77 75]
 [52 62 13  6 93]
 [42 90 17 65 47]]


In [ ]:
np.sum(arr)
np.mean(arr)
np.median(arr)
np.std(arr)
np.min(arr)
np.max(arr)
np.argmin(arr) # return the index of minimum value
np.argmax(arr) # return the index of maximum value
np.argsort(arr) # return the indices that would sort the array

array([[2, 1, 0, 4, 3],
       [3, 2, 0, 1, 4],
       [2, 0, 4, 3, 1]])

In [52]:
print(arr)

[[64 26 24 77 75]
 [52 62 13  6 93]
 [42 90 17 65 47]]


In [53]:
np.sum(arr, axis=0) # sum along columns

array([158, 178,  54, 148, 215])

In [54]:
np.sum(arr, axis=1) # sum along rows

array([266, 226, 261])

### Broadcasting

In [55]:
arr = np.random.randint(0,100,(3,5))
print(arr)

[[98 92 25 16 16]
 [11 75 83 96 26]
 [88 13 10 37 43]]


In [56]:
arr + 5

array([[103,  97,  30,  21,  21],
       [ 16,  80,  88, 101,  31],
       [ 93,  18,  15,  42,  48]], dtype=int32)

### Boolean Masking

In [58]:
arr_mas = arr[arr>50] # boolean indexing
print(arr_mas)

[98 92 75 83 96 88]


In [59]:
arr[ arr % 2 == 0 ] # boolean indexing for even numbers

array([98, 92, 16, 16, 96, 26, 88, 10], dtype=int32)

### Random Modules

In [ ]:
np.random.seed(42) # is used to control randomness so that your results are reproducible.
arr1 = np.random.randn(3,3)
print(arr1)
arr2 = np.random.rand(3,3)
print(arr2)
arr3 = np.random.randint(1,10,5)
print(arr3)

[[ 0.13442888 -0.16820509  1.16476865]
 [-0.24574769 -0.76966777  1.21217234]
 [ 1.2334968  -1.57415529  0.63795294]]
[[0.56124343 0.38292687 0.9717121 ]
 [0.84891382 0.72172952 0.23598492]
 [0.25606832 0.04043359 0.71066289]]
[3 7 1 4 4]
